run:
  timeout: 5m
  go: '1.24'
  modules-download-mode: readonly
  tests: true
  build-tags: []

output:
  formats:
    - format: json
      path: metrics/report.json
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive
    - gosec
  disable:
    - typecheck
  disable-all: false

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
    enable-all: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/andro-kes/gokode
  gocritic:
    enabled-checks:
      - appendAssign
      - assignOp
      - badCond
      - boolExprSimplify
      - captLocal
      - caseOrder
      - defaultCaseOrder
      - dupArg
      - dupBranchBody
      - dupCase
      - elseif
      - emptyFallthrough
      - emptyStringTest
      - hexLiteral
      - ifElseChain
      - regexpMust
      - sloppyLen
      - switchTrue
      - typeSwitchVar
      - underef
      - unlabelStmt
      - unslice
  revive:
    confidence: 0.8
  gosec:
    excludes:
      - G104

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - linters:
        - typecheck
      text: "cannot range over"
